const MODULE = 'ASSESSMENT';

export const CLEAR_INPUT = `${MODULE}/CLEAR_INPUT`;
export const HANDLE_INPUT = `${MODULE}/HANDLE_INPUT`;
export const HANDLE_VALIDATION = `${MODULE}/HANDLE_VALIDATION`;

export const SUBMIT_REQUEST = `${MODULE}/SUBMIT_REQUEST`;
export const SUBMIT_SUCCESS = `${MODULE}/SUBMIT_SUCCESS`;
export const SUBMIT_FAILURE = `${MODULE}/SUBMIT_FAILURE`;
